### ISSUE TITLE
puppeteer v8 is out

### ISSUE THREAD

**Issue by rafipiccolo** [PejmanNik/puppeteer-report#13]
According to the releases changelog : https://github.com/puppeteer/puppeteer/releases/tag/v8.0.0

Nothing concerns this package
```
#> git clone https://github.com/PejmanNik/puppeteer-report.git
#> grep -r ChromeArgOptions .
#> grep -r BrowserOptions .
```

so its safe to update peer dependencies

pull request done

**Comment by PejmanNik** [comment]
Thank you @rafipiccolo  👌

**Comment by PejmanNik** [comment]
V 2.0.4 has been released
