### ISSUE TITLE
Cannot use with Puppeteer 8.x

### ISSUE THREAD

**Issue by paambaati** [PejmanNik/puppeteer-report#17]
This is similar to https://github.com/PejmanNik/puppeteer-report/issues/16, except I can't move to `puppeteer-core` as I use `puppeteer`.

While there's no issues during runtime, TypeScript builds fail —

```
error TS2345: Argument of type 'import("/home/wizard/wiz-pdf/node_modules/puppeteer/lib/types").Page' is not assignable to parameter of type 'import("/home/wizard/wiz-pdf/node_modules/@types/puppeteer-core/node_modules/@types/puppeteer/index").Page'.
  Type 'Page' is missing the following properties from type 'Page': setMaxListeners, getMaxListeners, listeners, rawListeners, and 3 more.
```

I'm not entirely sure how to solve this in a backwards-compatible way; any ideas are welcome.

**Comment by PejmanNik** [comment]
Can we solve it by upgrading the `@types/puppeteer`  to the last version?

**Comment by paambaati** [comment]
We could try, but AFAIK, Puppeteer ships with it's own types starting from the [6.x](https://github.com/puppeteer/puppeteer/releases/tag/v6.0.0) release.

**Comment by PejmanNik** [comment]
the new version `2.0.5`  will fix it.

**Comment by paambaati** [comment]
@PejmanNik I can confirm that `2.0.5` does not fix this. Here's what I get when using `puppeteer@9.1.0` and `puppeteer-report@2.0.5` —

```
 error TS2345: Argument of type 'import("/Users/gp/Projects/wiz-pdf/node_modules/puppeteer/lib/types").Page' is not assignable to parameter of type 'import("/Users/gp/Projects/wiz-pdf/node_modules/@types/puppeteer-core/node_modules/@types/puppeteer/index").Page'.
  Type 'Page' is missing the following properties from type 'Page': setMaxListeners, getMaxListeners, listeners, rawListeners, and 3 more.

87     const pdf = await pdfPage(page, {
                                 ~~~~

Found 1 error.

```

**Comment by PejmanNik** [comment]
@paambaati please confirm the new version fixes this issue.
Thank you.

**Comment by PejmanNik** [comment]
@paambaati Thank you 🎉
