### ISSUE TITLE
more/custom sections

### ISSUE THREAD

**Issue by dkern** [PejmanNik/puppeteer-report#26]
Would it be possible to customize the sections and add different ones? Actually only two areas `header` and `footer` are supported. But for example, I currently need to create pdf files with three fixes sections on each page. Obviously a header and a footer, but also a vertically oriented text on the left side of each page.

I don't know how to archive this otherwise. Thanks.

**Comment by PejmanNik** [comment]
I think this answer may help you:
https://stackoverflow.com/questions/49970317/repeating-a-watermark-on-every-print-page-javascript-or-css

If not, please let me know. You can implement it like how I handle header/footer, but it will not be easy to do.

**Comment by dkern** [comment]
Thank you for that. I would need to test if i can get this working with different html elements too. The 100vh could be an idea.

But even then, in general it would be nice feature, to add more areas to the rendering. I don't know how hard this would be, but that is currently the only limitation i see for this add-on. But i have no idea how hard this would be to implement. ;) 

I will test if i get something like this working with that 100vh and let you know. But this may take some days. Thanks!

**Comment by PejmanNik** [comment]
You're welcome. I agree that it is nice to have but implement it may take a while and need more attention on this issue. also, I'm open to PR.

**Comment by dkern** [comment]
I tried to use a background image. But I ran into another Problem. I can't put a background behind the footer or header. So my background image (in this case a text) will be cut when the footer is placed above it. Is there any way to have a overall page background?

**Comment by PejmanNik** [comment]
sorry I miss your comment. It is not possible because the header and footer will generate separately and override the page. I think a hacky solution would be to cut the image into 3 part and adjust it with CSS. please let me know if you try it.

**Comment by dkern** [comment]
That's not working for me. In my case I had to add a very small vertical oriented disclaimer text on the left side. I found no other way than making the text shorter and put it into an SVG to set it as background of a 100vh content element. But as the header and footer of my document are pretty large, the text becomes very small.

That brings me back to my initial request, to have multiple areas like header & footer. So if it would be possible to add a third area, it would be easy to apply a text over the document. But for now, I found no better solution.

I even took a look to the code, but I'm not able to make a decent PR out of my wish. 😉

**Comment by PejmanNik** [comment]
The current lib uses a hack to make it possible to have a header and footer and there is not much room to customize but I'm working on a new way that will resolve this issue and open a way to customize the render process. you can check the progress in #12
