### ISSUE TITLE
Mandatory dependency to rollup not mentioned in README

### ISSUE THREAD

**Issue by HunteRoi** [PejmanNik/puppeteer-report#27]
You don't mention anywhere that you use [rollup](https://www.npmjs.com/package/rollup) to build your bundle and this lets people in the dark when it comes to using it.

Indeed, if you don't have rollup installed in your global packages, you have to 
1) find what is rollup
2) double check that you have the right package
3) install it
4) rerun `npm run build` and pray for it to work

I think you should clearly state that this is a mandatory dependency to building your library.

**Comment by PejmanNik** [comment]
Yes, It was only used to port the package for other languages, and it was not commonly used by anyone except me :)) also this is a free/open-source project. you can always improve it with a PR.

**Comment by PejmanNik** [comment]
As I checked `rollup` is in the dependency of the project in the last version on this package,  the issue was in submodules inside `puppeteer-report-csharp`.
