### ISSUE TITLE
Landscape print results in footer wrong offset

### ISSUE THREAD

**Issue by webbkvalite** [PejmanNik/puppeteer-report#28]
When printing in portrait mode, page numbering works fine in footer.
When switching to landscape mode, page numbering in footer is out of pdf-page boundaries.
This is the page when I print it manually without puppeteer, the page numbering ("Sida") is not populated:
![image](https://user-images.githubusercontent.com/8328896/127164577-b954c279-56d0-4f72-9517-e7606d0230c5.png)

This is the page through puppeteer, page numbering is missing:
![image](https://user-images.githubusercontent.com/8328896/127164854-3ddc3b96-9e1d-4404-a8c3-7f322c89bd1f.png)

This is the page through puppeteer with custom page width, then the page numbering is visible again, but too far off:
![image](https://user-images.githubusercontent.com/8328896/127165031-d351a807-fea1-446d-95d5-766d40dda65e.png)

I have tried every combination of PdfOptions. Is there a solution to this?

Thank you!!

/Martin

**Comment by PejmanNik** [comment]
Hi, I can't see any issue with the latest version. please provide an HTML file so I can reproduce the issue.

![image](https://user-images.githubusercontent.com/18081640/127747505-c5780bbf-b318-4256-993b-906a9ff81927.png)

**Comment by webbkvalite** [comment]
Thank you Pejman!

Here are the files. I'm leaving on vacation tomorrow for 4 weeks, so I'll not be able to reply for some time.

Appreciate your help.

/Martin
[test.zip](https://github.com/PejmanNik/puppeteer-report/files/6912133/test.zip)

**Comment by PejmanNik** [comment]
No problem. You put footer in a table so the lib can't handle it. you can check the `examples` folder.
