### ISSUE TITLE
Is it possible to have the content of the pdf overlap the footer?

### ISSUE THREAD

**Issue by PritamSangani** [PejmanNik/puppeteer-report#29]
Hi! Thank you for developing this awesome library - it makes it much easier to include a footer for puppeteer pdf generation!

I was wondering if it was possible, either via options or CSS, to have the footer and content overlap, with the footer appearing underneath the content?

I am looking to achieve something like this:
<img width="979" alt="Screenshot 2021-07-31 at 20 49 13" src="https://user-images.githubusercontent.com/22857896/127751014-0a178a40-7f0d-4e67-9b0e-d82f163dbdda.png">

With the graphic being part of the footer appearing on all pages and the box with the grey border being part of the page. Not all pages will have the content overlapping the footer.

**Comment by martynhoyer** [comment]
I tried something similar using all kinds of CSS trickery - `position: absolute`, `position: fixed`, viewport units etc. and couldn't get anywhere. I think the way it works under the hood means there's essentially 3 `<html>` elements which sort of get concatenated together, so their contents are completely unrelated during the build, which means you'll struggle with any overlapping.

I could be wrong, but I gave up in the end.

**Comment by PejmanNik** [comment]
@martynhoyer is right you can't do it. but maybe we can play some hack if you have static content to overlap like the image. please prepare a sample HTML page I will try it.

**Comment by PejmanNik** [comment]
The current lib uses a hack to make it possible to have a header and footer and there is not much room to customize but I'm working on a new way that will resolve this issue and open a way to customize the render process. you can check the progress in #12
