### ISSUE TITLE
Print background css

### ISSUE THREAD

**Issue by swamidass** [PejmanNik/puppeteer-report#37]
Is there a way to pass through options to the browser's PDF render? In particular, it seems that printBackground needs to be set to true in order to correctly render some parts of my layout. How can I ensure that is done?

**Comment by PejmanNik** [comment]
Please check the readme. the `pdfPage` and `pdf` accept the original puppeteer PDF options. you can pass the printBackground  in both functions.

https://github.com/PejmanNik/puppeteer-report#pdf

**Comment by swamidass** [comment]
Thanks.
