### ISSUE TITLE
Netlify build fails because module puppeteer is missing

### ISSUE THREAD

**Issue by mckraemer** [PejmanNik/puppeteer-report#4]
Hi,

first thank you for this module. I can't get this to work with aws lambda on Netlify and Puppeteer-Core. During the build it always fails with:
`Error: In file "/opt/build/repo/lambda/pdf/pdf.js": Cannot find module 'puppeteer'`
I thought puppeteer is a peer dependency and I could use core as well.

Greetings

**Comment by PejmanNik** [comment]
Hi, Thank you for using this lib. do you follow the readme?

I think this part will help you:
https://github.com/PejmanNik/puppeteer-report#note-1

you need to use `pdfPage` function

**Comment by mckraemer** [comment]
Hi,
thanks for the answer. I have copied part of my code, maybe this will help. :) 

`const fs = require('fs')
const handlebars = require('handlebars')
const puppeteer = require('puppeteer-core')
const report = require('puppeteer-report')

const oPage = await oBrowser.newPage()
await oPage.setContent(html)

const oPDF = await pdfPage(oPage, {
      format: 'A4',
      margin: { top: '2cm', right: '2cm', bottom: '2.5cm', left: '2.5cm' },
 })
`

**Comment by PejmanNik** [comment]
I test it with `chrome-aws-lambda` and can't see the issue.. can you please create a simple repo that helps me to reproduce this issue? Thank you

**Comment by mckraemer** [comment]
https://github.com/mckraemer/netlify-report

Tried it again, error:
`2:15:49 AM:   A Netlify Function failed to require one of its dependencies.
2:15:49 AM:   If the dependency is a Node module, please make sure it is present in the site's top-level "package.json".
  If it is a local file instead, please make sure the file exists and its filename is correctly spelled.
2:15:49 AM: ​
2:15:49 AM:   In file "/opt/build/repo/lambda/pdf/pdf.js"
2:15:49 AM:   Cannot find module 'puppeteer'`

**Comment by PejmanNik** [comment]
It is very strange the puppeteer only required when you use the pdf function but I do some tests and the issue exist in the Netlify :(

**Comment by PejmanNik** [comment]
I think it is Netlify builder issue. because they don't support dynamic require. I use this code:

```js
exports.handler = async (event, context) => {
   if ( 1 === 3)
   {
	   require("xxx.js");
   }
}
```

And got this error

![image](https://user-images.githubusercontent.com/18081640/100893632-cfdad880-34d0-11eb-9697-06322bc3fd5f.png)

**Comment by PejmanNik** [comment]
The only recommendation for this issue is: clone the repo remove the pdf function and use it directly in your project.

**Comment by PejmanNik** [comment]
Please feel free to reopen the issue if there is anything we can do about this issue.
Thank you
