### ISSUE TITLE
Doesn't work properly with variable page sizes (1st page A3 landscape, other pages A4 portrait)

### ISSUE THREAD

**Issue by leqwasd** [PejmanNik/puppeteer-report#40]
I have CSS rules like this:
```css
@page:first {
    size: A3 landscape;
}
@page {
    size: A4 portrait;
}
```

Basically - my first page is the main document, and it needs to be in the size specified. All of the other pages are utility pages, so those need to be in A4 portrait format.

Now it calculates only 1 footer size, and applies it to all of the pages. Since the firs footer was larger, it doesn't fit in other pages which are smaller.

Edit: OK, I get it - thats how chromium works.
But there is still another issue - 
If you have header and footer - 

When you render headers/footers in the second run - you put them each in a different page.
it breaks - becaus "footer" will not be rendered in "@page:first" - and the size wont be correct.

EDIT: Ok, chromium sucks at printing varying page sizes.. It also takes height as from the first page...

**Comment by PejmanNik** [comment]
It is not possible to such customization by the current library. You can create separate PDf and then merge them together.
For the footer issues, unfortunately, this approach can not handle it.

Hopefully, soon I will release the new library, and such a problem has already been fixed there.
