### ISSUE TITLE
Feature: Option to Set Full Page Background, ignore the page margins

### ISSUE THREAD

**Issue by Nstd** [PejmanNik/puppeteer-report#42]
The content page may need margins to be properly displayed. if not set top and bottom margins, the position where page breaked will reach top or bottom edge of the paper. If page margins set,  the page background in html body won't  be full page.

**Comment by PejmanNik** [comment]
This is the puppeteer limitation. You can search for it. Maybe there is a workaround, but this package can't do anything about it.

I'm working on a new project that will solve your problem, you can follow it in #12, but I think the first beta version will be ready in 2 months.
