### ISSUE TITLE
Hiding header moves footer to top of page

### ISSUE THREAD

**Issue by jpike88** [PejmanNik/puppeteer-report#43]
This library isn't really useful in a case where I want the header to show only on the first page. All subsequent pages have this ugly gap up the top if I use the onChange method to set visibility:hidden. But if I use display:none, or height:0px, margin:0px etc, my footer jumps up to the top of each page instead.

There needs to be a better way to handle this

**Comment by PejmanNik** [comment]
This is the puppeteer limitation. this package can't do anything about it.

I'm working on a new project that will solve your problem, you can follow it at https://github.com/PejmanNik/puppeteer-report/issues/12
