### ISSUE TITLE
PDF creation reaches timeout for big PDFs

### ISSUE THREAD

**Issue by adidaslevy** [PejmanNik/puppeteer-report#45]
**Issue Description**

When using the puppeteer pdf, PDFOptions comes with a timeout parameter, allowing the developer to turn it off.
With puppeteer-report it's not possible. the timeout is fixed for 30000ms. 

And I keep getting this annoying message:
`{"service":"reports-render-service","timestampString":"2022-03-15 15:34:19","logInfo":{"error":"waiting for Page.printToPDF failed: timeout 30000ms exceeded","correlationId":"62307e6ffd8d891c0be0b82d","fileName":"report-snapshots.service.js","functionName":"urlToPDF"}`

This is the pdfOptions const: 
`const pdfConfig: PDFOptions = {
  path: "" ,
  format: "a4",
  printBackground: true,
  margin: {
    top: "30px",
    bottom: "0px",
  }
}`

This is the method call: 
`
import report from "puppeteer-report";
await report.pdfPage(this.page, pdfConfig);`

**Request**
Expose timeout to user

**Comment by PejmanNik** [comment]
Fixed in the 3.0.2

**Comment by adidaslevy** [comment]
Thanks!
