### ISSUE TITLE
puppeteer-report does not take into account the scale attribute

### ISSUE THREAD

**Issue by ELOUFIR** [PejmanNik/puppeteer-report#5]
Hi 
First, thank you for this module. I pass the scale attribute to **report.pdfPage(page, options)** but it always use the original height of my header instead of multiple it by the scale that I provided.

I manage to fix that in my local by editing the _pdfPage_ function to this :

```diff
async function pdfPage(page: Page, options?: PDFOptions): Promise<Uint8Array> {
  const { path, ...pdfOptions } = options ?? {};
  const margin = {
    marginTop: pdfOptions?.margin?.top ?? 0,
    marginBottom: pdfOptions?.margin?.bottom ?? 0,
  };

  const [getHeightFunc, getHeightArg] = core.getHeightEvaluator(
    margin.marginTop,
    margin.marginBottom
  );
-* const { headerHeight, footerHeight } = await page.evaluate(
+* let { headerHeight, footerHeight } = await page.evaluate(
    getHeightFunc,
    getHeightArg
  );
  
+*  if (pdfOptions?.scale) {
+*   headerHeight *= pdfOptions.scale;
+*   footerHeight *= pdfOptions.scale;
+*  }
```

Greetings

**Comment by PejmanNik** [comment]
Hi, Thank you. Yes, you are right It doesn't support scale. 
Thank you for the modification. Can you please send it as a PR?

**Comment by ELOUFIR** [comment]
DONE @PejmanNik .

**Comment by paambaati** [comment]
@PejmanNik Would you mind publishing a release with this fix please?

**Comment by PejmanNik** [comment]
@paambaati done!
