### ISSUE TITLE
Use a readable stream

### ISSUE THREAD

**Issue by ozanbaskan** [PejmanNik/puppeteer-report#51]
Instead of returning the raw pdf there could be an option to return a readable stream.

**Comment by PejmanNik** [comment]
if you don't pass the path property to pdf method, it will return a byte array

https://github.com/PejmanNik/puppeteer-report/issues/36

**Comment by ozanbaskan** [comment]
I am suggesting a  returning a readable stream so I can pipe it to the writable stream for the http connection so for larger pdf files I don't run out of memory.

**Comment by PejmanNik** [comment]
oh I see, as this project uses Puppeteer for creating PDFs, I can't do anything about it until Puppeteer supports this
